@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "Usuário", "quem vai usar o sistema")

Boundary(cashFlow, "Contexto do Fluxo de Caixa") {
    System(cashFlowApi, "API Fluxo de Caixa", "onde pode ser registrado os lançamentos diário")
    SystemDb(cashFlowDb, "Banco de Dados", "onde os dados são registrados")
}

Rel_D(user, cashFlowApi, "usa")
Rel_D(cashFlowApi, cashFlowDb, "usa")

@enduml